obj-$(CONFIG_HAGENT) += hagent.o hagent_balloon.o hagent_placement.o

RUSTFLAGS_lib.o += --extern hashbrown --extern lazy_static

hagent-objs += helper.o migrate.o param.o hook.o lib.o

hagent_balloon-objs += balloon.o

hagent_placement-objs += placement.o
