#ifndef PARAM_H
#define PARAM_H

#include "envconst.h"

ENVCONST(DRAMSIZE, ulong, 4L * (1024L * 1024L * 1024L))
ENVCONST(NVMSIZE, ulong, 4L * (1024L * 1024L * 1024L))
ENVCONST(SMALLALLOCSIZE, ulong, 1L << 30)

ENVSTR(DRAMPATH, "/dev/dax0.0")
ENVSTR(NVMPATH, "/dev/dax1.0")

ENVCONST(FAULT_THREAD_CPU, ulong, 0)
ENVCONST(SCANNING_THREAD_CPU, ulong, 1)
ENVCONST(MIGRATION_THREAD_CPU, ulong, 2)
ENVCONST(STATS_THREAD_CPU, ulong, 3)

ENVCONST(PEBS_KSWAPD_MIGRATE_RATE_BYTE, ulong, 10UL << 30)
ENVCONST(HOT_READ_THRESHOLD, ulong, 4)
ENVCONST(HOT_WRITE_THRESHOLD, ulong, 4)
ENVCONST(PEBS_COOLING_THRESHOLD, ulong, 10)

ENVCONST(HOT_RING_REQS_THRESHOLD, ulong, 1024 * 1024)
ENVCONST(COLD_RING_REQS_THRESHOLD, ulong, 128)
ENVCONST(CAPACITY, ulong, 16 * 1024 * 1024)
ENVCONST(COOLING_PAGES, ulong, 8192)

// #define PEBS_NPROCS 4
ENVCONST(PEBS_NPROCS, ulong, 4) // Has to be == 1+2^n
ENVCONST(PERF_PAGES, ulong, 1 + (2 << 9)) // Has to be == 1+2^n
ENVCONST(SAMPLE_PERIOD, ulong, 19997)
// ENVCONST(SAMPLE_PERIOD, ulong, 10007)
// ENVCONST(SAMPLE_PERIOD, ulong, 100)

#define BASEPAGE_SIZE (4UL * 1024UL)
#define HUGEPAGE_SIZE (2UL * 1024UL * 1024UL)
#define GIGAPAGE_SIZE (1024UL * 1024UL * 1024UL)
#define PAGE_SIZE HUGEPAGE_SIZE

#define FASTMEM_PAGES ((DRAMSIZE) / (PAGE_SIZE))
#define SLOWMEM_PAGES ((NVMSIZE) / (PAGE_SIZE))

#define BASEPAGE_MASK (BASEPAGE_SIZE - 1)
#define HUGEPAGE_MASK (HUGEPAGE_SIZE - 1)
#define GIGAPAGE_MASK (GIGAPAGE_SIZE - 1)

#define BASE_PFN_MASK (BASEPAGE_MASK ^ UINT64_MAX)
#define HUGE_PFN_MASK (HUGEPAGE_MASK ^ UINT64_MAX)
#define GIGA_PFN_MASK (GIGAPAGE_MASK ^ UINT64_MAX)

#define MAX_UFFD_MSGS (1)
#define MAX_COPY_THREADS (4)

// #define USE_DMA
#define NUM_CHANNS 2
#define SIZE_PER_DMA_REQUEST (1024 * 1024)

#endif
